In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('raw data.csv')
df

    시군구  스포츠용품  스포츠시설  박물관  문화재  해수욕장  휴양림  공연장  미술관  맛집
0   고령군     10      2   17   31     0   12    7    1   0
1   해남군     15      6    9   40    23   11    7    5   0
2   사하구     40     45    2    4    40    0    4   12   3
3   보성군     12      2   11   28    31   60    5    9   1
4   곡성군      9      5    6   39     0    1    8    3   0
..  ...    ...    ...  ...  ...   ...  ...  ...  ...  ..
64  거제시     64    123   11   62    66   46    8    3  30
65  진안군      4      5   19   27     0   55    3    6   0
66  예천군     14      7    3   74     0   27    5    4   1
67  합천군     10      6   19   88     0   31    5    4   0
68  사천시     30     85   11   22    14    6    7    2   4

[69 rows x 10 columns]

In [3]:
df.loc['합계'] = df.iloc[:, 1:].sum()
df.iat[69, 0] = '합계'
df['합계'] = df.sum(axis=1)
df

C:\Users\young0tete\AppData\Local\Temp\ipykernel_11240\56832156.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df['합계'] = df.sum(axis=1)

,시군구,스포츠용품,스포츠시설,박물관,문화재,해수욕장,휴양림,공연장,미술관,맛집,합계
0,고령군,10.0,2.0,17.0,31.0,0.0,12.0,7.0,1.0,0.0,80.0
1,해남군,15.0,6.0,9.0,40.0,23.0,11.0,7.0,5.0,0.0,116.0
2,사하구,40.0,45.0,2.0,4.0,40.0,0.0,4.0,12.0,3.0,150.0
3,보성군,12.0,2.0,11.0,28.0,31.0,60.0,5.0,9.0,1.0,159.0
4,곡성군,9.0,5.0,6.0,39.0,0.0,1.0,8.0,3.0,0.0,71.0
...,...,...,...,...,...,...,...,...,...,...,...
65,진안군,4.0,5.0,19.0,27.0,0.0,55.0,3.0,6.0,0.0,119.0
66,예천군,14.0,7.0,3.0,74.0,0.0,27.0,5.0,4.0,1.0,135.0
67,합천군,10.0,6.0,19.0,88.0,0.0,31.0,5.0,4.0,0.0,163.0
68,사천시,30.0,85.0,11.0,22.0,14.0,6.0,7.0,2.0,4.0,181.0
합계,합계,3128.0,2179.0,881.0,3122.0,820.0,1630.0,577.0,415.0,400.0,13152.0

In [4]:
#카테고리별 해당 지역의 비율
df1=df.copy()

for i in range(1, 10):
    for j in range(69):
        df1.iat[j, i] = df1.iat[j,i]/df1.iat[69,i]

df1

,시군구,스포츠용품,스포츠시설,박물관,문화재,해수욕장,휴양림,공연장,미술관,맛집,합계
0,고령군,0.003197,0.000918,0.019296,0.009930,0.000000,0.007362,0.012132,0.002410,0.0000,80.0
1,해남군,0.004795,0.002754,0.010216,0.012812,0.028049,0.006748,0.012132,0.012048,0.0000,116.0
2,사하구,0.012788,0.020652,0.002270,0.001281,0.048780,0.000000,0.006932,0.028916,0.0075,150.0
3,보성군,0.003836,0.000918,0.012486,0.008969,0.037805,0.036810,0.008666,0.021687,0.0025,159.0
4,곡성군,0.002877,0.002295,0.006810,0.012492,0.000000,0.000613,0.013865,0.007229,0.0000,71.0
...,...,...,...,...,...,...,...,...,...,...,...
65,진안군,0.001279,0.002295,0.021566,0.008648,0.000000,0.033742,0.005199,0.014458,0.0000,119.0
66,예천군,0.004476,0.003212,0.003405,0.023703,0.000000,0.016564,0.008666,0.009639,0.0025,135.0
67,합천군,0.003197,0.002754,0.021566,0.028187,0.000000,0.019018,0.008666,0.009639,0.0000,163.0
68,사천시,0.009591,0.039009,0.012486,0.007047,0.017073,0.003681,0.012132,0.004819,0.0100,181.0
합계,합계,3128.000000,2179.000000,881.000000,3122.000000,820.000000,1630.000000,577.000000,415.000000,400.0000,13152.0

In [5]:
#역내 해당 카테고리의 비율
df2=df.copy()

for i in range(69):
    for j in range(1, 10):
        df2.iat[i, j] = df2.iat[i, j]/df2.iat[i, 10]

df2

,시군구,스포츠용품,스포츠시설,박물관,문화재,해수욕장,휴양림,공연장,미술관,맛집,합계
0,고령군,0.125000,0.025000,0.212500,0.387500,0.000000,0.150000,0.087500,0.012500,0.000000,80.0
1,해남군,0.129310,0.051724,0.077586,0.344828,0.198276,0.094828,0.060345,0.043103,0.000000,116.0
2,사하구,0.266667,0.300000,0.013333,0.026667,0.266667,0.000000,0.026667,0.080000,0.020000,150.0
3,보성군,0.075472,0.012579,0.069182,0.176101,0.194969,0.377358,0.031447,0.056604,0.006289,159.0
4,곡성군,0.126761,0.070423,0.084507,0.549296,0.000000,0.014085,0.112676,0.042254,0.000000,71.0
...,...,...,...,...,...,...,...,...,...,...,...
65,진안군,0.033613,0.042017,0.159664,0.226891,0.000000,0.462185,0.025210,0.050420,0.000000,119.0
66,예천군,0.103704,0.051852,0.022222,0.548148,0.000000,0.200000,0.037037,0.029630,0.007407,135.0
67,합천군,0.061350,0.036810,0.116564,0.539877,0.000000,0.190184,0.030675,0.024540,0.000000,163.0
68,사천시,0.165746,0.469613,0.060773,0.121547,0.077348,0.033149,0.038674,0.011050,0.022099,181.0
합계,합계,3128.000000,2179.000000,881.000000,3122.000000,820.000000,1630.000000,577.000000,415.000000,400.000000,13152.0

In [6]:
#카테고리별 rescaling
df3=df.copy()
df3 = df3.drop(df3.index[-1])

for i in range(1, 10):
    min_val = df3.iloc[:, i].min() 
    max_val = df3.iloc[:, i].max() 
    
    for j in range(69):
        df3.iat[j, i] = (df3.iat[j, i] - min_val) / (max_val - min_val)

df3

,시군구,스포츠용품,스포츠시설,박물관,문화재,해수욕장,휴양림,공연장,미술관,맛집,합계
0,고령군,0.049261,0.000000,0.278689,0.103333,0.000000,0.076923,0.194444,0.043478,0.000000,80.0
1,해남군,0.073892,0.021858,0.147541,0.133333,0.106977,0.070513,0.194444,0.217391,0.000000,116.0
2,사하구,0.197044,0.234973,0.032787,0.013333,0.186047,0.000000,0.111111,0.521739,0.069767,150.0
3,보성군,0.059113,0.000000,0.180328,0.093333,0.144186,0.384615,0.138889,0.391304,0.023256,159.0
4,곡성군,0.044335,0.016393,0.098361,0.130000,0.000000,0.006410,0.222222,0.130435,0.000000,71.0
...,...,...,...,...,...,...,...,...,...,...,...
64,거제시,0.315271,0.661202,0.180328,0.206667,0.306977,0.294872,0.222222,0.130435,0.697674,413.0
65,진안군,0.019704,0.016393,0.311475,0.090000,0.000000,0.352564,0.083333,0.260870,0.000000,119.0
66,예천군,0.068966,0.027322,0.049180,0.246667,0.000000,0.173077,0.138889,0.173913,0.023256,135.0
67,합천군,0.049261,0.021858,0.311475,0.293333,0.000000,0.198718,0.138889,0.173913,0.000000,163.0
68,사천시,0.147783,0.453552,0.180328,0.073333,0.065116,0.038462,0.194444,0.086957,0.093023,181.0

In [7]:
df4=df2+df3
df4.iloc[:, 0] = df2.iloc[:, 0]
df4 = df4.drop(df4.index[-1])
df4

,시군구,스포츠용품,스포츠시설,박물관,문화재,해수욕장,휴양림,공연장,미술관,맛집,합계
0,고령군,0.174261,0.025000,0.491189,0.490833,0.000000,0.226923,0.281944,0.055978,0.000000,160.0
1,해남군,0.203202,0.073582,0.225127,0.478161,0.305253,0.165340,0.254789,0.260495,0.000000,232.0
2,사하구,0.463711,0.534973,0.046120,0.040000,0.452713,0.000000,0.137778,0.601739,0.089767,300.0
3,보성군,0.134585,0.012579,0.249510,0.269434,0.339155,0.761974,0.170335,0.447908,0.029545,318.0
4,곡성군,0.171096,0.086816,0.182868,0.679296,0.000000,0.020495,0.334898,0.172688,0.000000,142.0
...,...,...,...,...,...,...,...,...,...,...,...
64,거제시,0.470235,0.959023,0.206962,0.356788,0.466783,0.406252,0.241593,0.137699,0.770314,826.0
65,진안군,0.053318,0.058410,0.471139,0.316891,0.000000,0.814749,0.108543,0.311290,0.000000,238.0
66,예천군,0.172669,0.079174,0.071403,0.794815,0.000000,0.373077,0.175926,0.203543,0.030663,270.0
67,합천군,0.110611,0.058668,0.428040,0.833211,0.000000,0.388902,0.169564,0.198453,0.000000,326.0
68,사천시,0.313529,0.923165,0.241101,0.194880,0.142464,0.071611,0.233118,0.098006,0.115123,362.0

In [8]:
# 두 개의 시리즈 생성 (예시)
s1 = pd.Series(df4.iloc[:, 0], name='시군구')
s2 = pd.Series(df4.iloc[:, 1]+df4.iloc[:, 2], name='스포츠')
s3 = pd.Series(df4.iloc[:, 3]+df4.iloc[:, 4], name='역사')
s4 = pd.Series(df4.iloc[:, 5]+df4.iloc[:, 6], name='자연힐링')
s5 = pd.Series(df4.iloc[:, 7]+df4.iloc[:, 8], name='문화예술')
s6 = pd.Series(df4.iloc[:, 9]+df4.iloc[:, 9]+df4.iloc[:, 9], name='맛집')

# 데이터프레임으로 합치기 (열 방향으로 합침)
df5 = pd.concat([s1, s2, s3, s4, s5, s6], axis=1)
df5

    시군구       스포츠        역사      자연힐링      문화예술        맛집
0   고령군  0.199261  0.982022  0.226923  0.337923  0.000000
1   해남군  0.276784  0.703288  0.470593  0.515284  0.000000
2   사하구  0.998684  0.086120  0.452713  0.739517  0.269302
3   보성군  0.147164  0.518944  1.101128  0.618244  0.088635
4   곡성군  0.257912  0.862163  0.020495  0.507587  0.000000
..  ...       ...       ...       ...       ...       ...
64  거제시  1.429258  0.563750  0.873035  0.379291  2.310941
65  진안군  0.111728  0.788030  0.814749  0.419833  0.000000
66  예천군  0.251843  0.866217  0.373077  0.379469  0.091990
67  합천군  0.169279  1.261250  0.388902  0.368017  0.000000
68  사천시  1.236694  0.435982  0.214075  0.331125  0.345368

[69 rows x 6 columns]

In [9]:
df5.to_csv('전처리 ver4.csv', index=False)